# Generated by Django 4.2.5 on 2023-09-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_choice_votes_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_able_to_vote',
        ),
    ]
